#!/usr/bin/env bash

set -euo pipefail

release_file=/etc/os-release

function install_snap_apps() {
  echo "Installing apps..."

	# media player
	echo "VLC Media Player"
	snap install vlc 
}

function update_apt() {
  apt update && apt -y upgrade
}

if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required."
  exit 1
fi

if grep -q "Ubuntu" $release_file
then
  update_apt
fi

if command -v snap > /dev/null 2>&1
then
        echo "Snap is already installed."
        install_snap_apps
else
        echo "Snap isn't installed."
        echo "Installation..."

        if grep -q "Ubuntu" $release_file
        then
          apt install snapd
          echo "Snap installation completed."
        fi

        install_snap_apps
fi
