#!/usr/bin/env bash

set -euo pipefail

release_file=/etc/os-release
pman_i_name="package-man-i"
pman_i_url="https://raw.githubusercontent.com/c-MatMaka-r/$pman_i_name/main/$pman_i_name"

function install_snap_apps() {
  echo "Installing apps..."

	# media player
	echo "VLC Media Player"
	snap install vlc 
}

# if not root do nothing
if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required."
  exit 1
fi

# universal script for upgrade eg. apt
if ! command -v package-man-u > /dev/null 2>&1
then
  curl -O "$pman_i_url"
  chmod +x "$pman_i_name"
  ./"$pman_i_name"
  rm ./"$pman_i_name"
fi

if command -v snap > /dev/null 2>&1
then
        echo "Snap is already installed."
        install_snap_apps
else
        echo "Snap isn't installed."
        echo "Installation..."

        if grep -q "Ubuntu" $release_file
        then
          apt install snapd
          echo "Snap installation completed."
        fi

        install_snap_apps
fi
